"""add orq_run_id to runs

Revision ID: 094d421180c8
Revises: 4da6c39cab68
Create Date: 2026-07-02 12:56:00.724165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094d421180c8'
down_revision: Union[str, Sequence[str], None] = '4da6c39cab68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('orq_run_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'orq_run_id')
    # ### end Alembic commands ###
