"""initial schema

Revision ID: 4838f0c60324
Revises: 
Create Date: 2026-07-02 11:11:18.590347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4838f0c60324'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('repo_url', sa.String(), nullable=True),
    sa.Column('workspace_path', sa.String(), nullable=True),
    sa.Column('base_branch', sa.String(), nullable=False),
    sa.Column('watch_prs', sa.Boolean(), nullable=False),
    sa.Column('watch_issues', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('serve_port', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('root', sa.String(), nullable=False),
    sa.Column('remote_url', sa.String(), nullable=True),
    sa.Column('base_branch', sa.String(), nullable=False),
    sa.Column('head_sha', sa.String(), nullable=True),
    sa.Column('current_branch', sa.String(), nullable=True),
    sa.Column('dirty', sa.Boolean(), nullable=False),
    sa.Column('managed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('executor', sa.String(), nullable=False),
    sa.Column('container_id', sa.String(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('api_port', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('base_sha', sa.String(), nullable=True),
    sa.Column('head_sha', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_cursors',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('offset', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_cursors')
    op.drop_table('runs')
    op.drop_table('repos')
    op.drop_table('projects')
    # ### end Alembic commands ###
