"""add webhook deliveries table

Revision ID: 4da6c39cab68
Revises: cafb4a47afdb
Create Date: 2026-07-02 11:32:58.424191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4da6c39cab68'
down_revision: Union[str, Sequence[str], None] = 'cafb4a47afdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook_deliveries')
    # ### end Alembic commands ###
